name: Pipeline
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          npm ci
          npm run test
      - uses: codecov/codecov-action@v1
        with:
          directory: ./tests/coverage/
